resource "local_file" "flutter" {
  content  = <<-EOT
    # This file is automatically generated by terraform
    # 10.0.2.2 is localhost for the android emulator
    # API_GATEWAY_URL="http://10.0.2.2:8000"
    API_GATEWAY_URL="${data.aws_ssm_parameter.api_gateway_url.value}"
    GIPHY_API_KEY="${data.aws_ssm_parameter.giphy_api_key.value}"
  EOT
  filename = "${local.root_dir}/.env.automated"
}
