resource "local_file" "flutter" {
  content  = <<-EOT
    # This file is automatically generated by terraform
    # 10.0.2.2 is localhost for the android emulator
    # API_GATEWAY_URL="http://10.0.2.2:8000"
    API_GATEWAY_URL="${data.aws_ssm_parameter.api_gateway_url.value}"
    GIPHY_API_KEY="${data.aws_ssm_parameter.giphy_api_key.value}"
    AUTOMATED_TESTER_USERNAME="${data.aws_ssm_parameter.automated_tester_username.value}"
    AUTOMATED_TESTER_PASSWORD="${data.aws_ssm_parameter.automated_tester_password.value}"
  EOT
  filename = "${local.root_dir}/.env.automated"
}

resource "local_file" "amplify_configuration" {
  content  = <<-EOT
    // This file is automatically generated by terraform
    const amplifyconfig = ''' {
        "UserAgent": "aws-amplify-cli/2.0",
        "Version": "1.0",
        "auth": {
            "plugins": {
                "awsCognitoAuthPlugin": {
                    "IdentityManager": {
                        "Default": {}
                    },
                    "CognitoUserPool": {
                        "Default": {
                            "PoolId": "${data.aws_ssm_parameter.cognito_pool_id.value}",
                            "AppClientId": "${data.aws_ssm_parameter.cognito_client_id.value}",
                            "Region": "ap-southeast-2"
                        }
                    },
                    "Auth": {
                        "Default": {
                            "authenticationFlowType": "USER_SRP_AUTH",
                            "OAuth": {
                                "WebDomain": "${data.aws_ssm_parameter.cognito_domain.value}",
                                "AppClientId": "${data.aws_ssm_parameter.cognito_client_id.value}",
                                "SignInRedirectURI": "myapp://",
                                "SignOutRedirectURI": "myapp://",
                                "Scopes": [
                                    "phone",
                                    "email",
                                    "openid",
                                    "profile",
                                    "aws.cognito.signin.user.admin"
                                ]
                            }
                        }
                    }
                }
            }
        }
    }''';
  EOT
  filename = "${local.root_dir}/lib/amplifyconfiguration.dart"
}
