name: qr_gif
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

# version: 1.0.1+2  # This is controlled by CICD

environment:
  sdk: "^3.0.0"

dependencies:
  enough_giphy_flutter: ^0.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  giphy_get: ^3.5.1
  http: ^1.1.0
  image: ^4.1.3
  amplify_flutter: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - .env.automated

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
