name: qr_gif
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

# version: 1.0.1+2  # This is controlled by CICD

environment:
  sdk: "^3.0.0"
  flutter: "^3.24.4"

dependencies:
  amplify_auth_cognito: ^2.5.0
  amplify_flutter: ^2.5.0
  amplify_secure_storage: ^0.5.7
  flex_color_scheme: ^8.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.2
  giphy_flutter_sdk: ^1.0.1
  http: ^1.2.2
  image: ^4.3.0
  path_provider: ^2.1.5
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - .env.automated

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
