name: qr_gif
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

# version: 1.0.1+2  # This is controlled by CICD

environment:
  sdk: "3.8.1"
  flutter: "3.32.8"

dependencies:
  amplify_auth_cognito: 2.6.5
  amplify_flutter: 2.6.5
  flex_color_scheme: 8.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: 5.2.1
  flutter_localizations:
    sdk: flutter
  get_it: 8.0.3
  giphy_flutter_sdk: 1.0.5
  http: 1.4.0
  path_provider: 2.1.5
  share_plus: 11.0.0

dev_dependencies:
  flutter_launcher_icons: 0.14.4
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
    
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - .env.automated

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
